### ISSUE TITLE
Bug: приходит пуш, если проголосовать за свой пост/комментарий

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/online-notify-service#1]
**Steps:**
1. авторизоваться
2. открыть свой пост/комментарий
3. проголосовать за него

**Expected result:** пуш не должен приходить, если голосуешь за свои посты/комментарии

**Actual result:** пуш приходит
**Comment:** https://sandbox.golos.io/

**Comment by Format-X22** [comment]
Было исправлено в другом тикете в другом сервисе.
